#!/bin/bash

# Run gofmt on all .go files
echo "Running gofmt..."
GOFMT_FILES=$(gofmt -l .)
if [ -n "${GOFMT_FILES}" ]; then
    echo "The following files need to be formatted:"
    echo "${GOFMT_FILES}"
    echo "Running gofmt -w ."
    gofmt -w .
    echo "Files formatted. Please stage the changes and try committing again."
    exit 1
fi

exit 0 